### ISSUE TITLE
cephfs  storageclass create pvc report error in setxattr

### ISSUE THREAD

**Issue by lklkxcxc** [kubernetes-incubator/external-storage#1148]
error log:
0314 13:37:58.993067       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim-local", UID:"563032cd-465e-11e9-ae0e-fa163e50a9c4", APIVersion:"v1", ResourceVersion:"562013", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": exit status 1
I0314 13:38:28.993466       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim-local", UID:"563032cd-465e-11e9-ae0e-fa163e50a9c4", APIVersion:"v1", ResourceVersion:"562013", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/claim-local"
E0314 13:38:29.195273       1 cephfs-provisioner.go:155] failed to provision share "kubernetes-dynamic-pvc-737d3b70-465e-11e9-8501-06b79445cad9" for "kubernetes-dynamic-user-737d3bb0-465e-11e9-8501-06b79445cad9", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 336, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 330, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 210, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 641, in create_volume
    self.fs.setxattr(path, 'ceph.dir.layout.pool_namespace', namespace, 0)
  File "cephfs.pyx", line 988, in cephfs.LibCephFS.setxattr (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/cephfs/pyrex/cephfs.c:10498)
cephfs.Error: (13, 'error in setxattr: error code 13')

image: quay.io/external_storage/cephfs-provisioner:v2.0.0-k8s1.11

ceph version:  ceph version 12.2.11

**Comment by wongma7** [comment]
it looks like a permissions issue. @cofyc any idea?

**Comment by cofyc** [comment]
what's your cephfs admin secret, is it auth key of ceph `client.admin`?
