### ISSUE TITLE
cephFs Provisoning is failed

### ISSUE THREAD

**Issue by kannanvr** [kubernetes-incubator/external-storage#1167]
Hi,
  cephFs provisoning is failed. Please guide me to resolve this issue

```
I0430 01:44:49.815730       1 controller.go:987] provision "default/claim2" class "cephfs": started
I0430 01:44:49.818926       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim2", UID:"282cd6ad-6ae9-11e9-9c78-14feb501f21c", APIVersion:"v1", ResourceVersion:"1159956", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/claim2"
^[[AE0430 01:47:06.112972       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-28ed5573-6ae9-11e9-8953-14feb501f21c" for "kubernetes-dynamic-user-28ed55d9-6ae9-11e9-8953-14feb501f21c", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 364, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 358, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 228, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
  File "/usr/local/bin/cephfs_provisioner", line 112, in volume_client
    self._volume_client.connect(None)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 471, in connect
    self.fs.mount()
  File "cephfs.pyx", line 548, in cephfs.LibCephFS.mount (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/cephfs/pyrex/cephfs.c:5648)
cephfs.Error: (110, 'error calling ceph_mount: error code 110')
W0430 01:47:06.113281       1 controller.go:746] Retrying syncing claim "default/claim2" because failures 1 < threshold 15
E0430 01:47:06.113324       1 controller.go:761] error syncing claim "default/claim2": failed to provision volume with StorageClass "cephfs": exit status 1
I0430 01:47:06.113367       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim2", UID:"282cd6ad-6ae9-11e9-9c78-14feb501f21c", APIVersion:"v1", ResourceVersion:"1159956", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": exit status 1
```

**Comment by kannanvr** [comment]
I solved this issue . Hence Closing it

**Comment by M258** [comment]
I met the same problem，can you tell me how to solve this issue

**Comment by M258** [comment]
> I solved this issue . Hence Closing it

I met the same issue, can you tell me how to solve it

**Comment by HristoA** [comment]
I have it the same here. When solve  something yourself please write down how you do it :)
