### ISSUE TITLE
[cephfs-provisioner] can not use args "enable-quota=true"

### ISSUE THREAD

**Issue by tomoncle** [kubernetes-incubator/external-storage#1173]
# [cephfs-provisioner] can not use args "enable-quota=true"
when i removed args "enable-quota=true" , it's work ok! 
I want to ask, is this a legacy bug or my configuration is wrong?

## ENV
* kube version: v1.10.6
* OS               : centos7
* ceph version: 12.2.10

## config
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cephfs-provisioner
  namespace: cephfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cephfs-provisioner
    spec:
      containers:
      - name: cephfs-provisioner
        image: "quay.io/external_storage/cephfs-provisioner:latest"
        securityContext:
          privileged: true
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/cephfs
        #- name: PROVISIONER_SECRET_NAMESPACE
        #  value: cephfs
        command:
        - "/usr/local/bin/cephfs-provisioner"
        args:
        - "-id=cephfs-provisioner-1" 
        - "-disable-ceph-namespace-isolation=true" 
        - "-enable-quota=true" 
      serviceAccount: cephfs-provisioner
```

## cephfs-provisioner pod log
```bash
[root@k8s-server-1 .dynamic]# kubectl logs -f -n cephfs cephfs-provisioner-5476d7c788-2rhp4 
I0507 06:37:56.897638       1 cephfs-provisioner.go:411] Creating CephFS provisioner ceph.com/cephfs with identity: cephfs-provisioner-1, secret namespace: 
I0507 06:37:56.905623       1 leaderelection.go:185] attempting to acquire leader lease  cephfs/ceph.com-cephfs...
I0507 06:38:14.646406       1 leaderelection.go:194] successfully acquired lease cephfs/ceph.com-cephfs
I0507 06:38:14.646694       1 controller.go:631] Starting provisioner controller ceph.com/cephfs_cephfs-provisioner-5476d7c788-2rhp4_a64b2288-7092-11e9-9c93-c68eac00c7fa!
I0507 06:38:14.649418       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"cephfs", Name:"ceph.com-cephfs", UID:"1ccc3caf-7070-11e9-86c7-fa163e0de3dc", APIVersion:"v1", ResourceVersion:"3956049", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' cephfs-provisioner-5476d7c788-2rhp4_a64b2288-7092-11e9-9c93-c68eac00c7fa became leader
I0507 06:38:14.748797       1 controller.go:680] Started provisioner controller ceph.com/cephfs_cephfs-provisioner-5476d7c788-2rhp4_a64b2288-7092-11e9-9c93-c68eac00c7fa!
I0507 06:43:46.354797       1 controller.go:987] provision "default/cephfs-web-dir-cefhfs-web-0" class "cephfs": started
I0507 06:43:46.365828       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"cephfs-web-dir-cefhfs-web-0", UID:"6837f6e4-7093-11e9-86c7-fa163e0de3dc", APIVersion:"v1", ResourceVersion:"3956939", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/cephfs-web-dir-cefhfs-web-0"
E0507 06:43:47.658559       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-76d7299c-7093-11e9-9c93-c68eac00c7fa" for "kubernetes-dynamic-user-76d72a85-7093-11e9-9c93-c68eac00c7fa", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 364, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 358, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 228, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 622, in create_volume
    self.fs.setxattr(path, 'ceph.quota.max_bytes', size.__str__(), 0)
  File "cephfs.pyx", line 988, in cephfs.LibCephFS.setxattr (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/cephfs/pyrex/cephfs.c:10498)
cephfs.OperationNotSupported: [Errno 95] error in setxattr
W0507 06:43:47.659039       1 controller.go:746] Retrying syncing claim "default/cephfs-web-dir-cefhfs-web-0" because failures 0 < threshold 15
E0507 06:43:47.659260       1 controller.go:761] error syncing claim "default/cephfs-web-dir-cefhfs-web-0": failed to provision volume with StorageClass "cephfs": exit status 1
I0507 06:43:47.659432       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"cephfs-web-dir-cefhfs-web-0", UID:"6837f6e4-7093-11e9-86c7-fa163e0de3dc", APIVersion:"v1", ResourceVersion:"3956939", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": exit status 1
I0507 06:44:02.659658       1 controller.go:987] provision "default/cephfs-web-dir-cefhfs-web-0" class "cephfs": started
I0507 06:44:02.837415       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"cephfs-web-dir-cefhfs-web-0", UID:"6837f6e4-7093-11e9-86c7-fa163e0de3dc", APIVersion:"v1", ResourceVersion:"3956939", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/cephfs-web-dir-cefhfs-web-0"
E0507 06:44:03.905021       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-80a6cc22-7093-11e9-9c93-c68eac00c7fa" for "kubernetes-dynamic-user-80a6cce1-7093-11e9-9c93-c68eac00c7fa", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 364, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 358, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 228, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 622, in create_volume
    self.fs.setxattr(path, 'ceph.quota.max_bytes', size.__str__(), 0)
  File "cephfs.pyx", line 988, in cephfs.LibCephFS.setxattr (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/cephfs/pyrex/cephfs.c:10498)
cephfs.OperationNotSupported: [Errno 95] error in setxattr
W0507 06:44:03.905362       1 controller.go:746] Retrying syncing claim "default/cephfs-web-dir-cefhfs-web-0" because failures 1 < threshold 15
E0507 06:44:03.905443       1 controller.go:761] error syncing claim "default/cephfs-web-dir-cefhfs-web-0": failed to provision volume with StorageClass "cephfs": exit status 1
I0507 06:44:03.905599       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"cephfs-web-dir-cefhfs-web-0", UID:"6837f6e4-7093-11e9-86c7-fa163e0de3dc", APIVersion:"v1", ResourceVersion:"3956939", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": exit status 1
```

**Comment by sdkfzv** [comment]
Hit the same issue...
It seems like the not match the condition "kernel client >= 4.17 but only on mimic clusters".
How to use the ceph-fuse to set the quota in cephfs-provisioner?
