### ISSUE TITLE
Cephfs: Dynamyc provisioning not working

### ISSUE THREAD

**Issue by deniskril** [kubernetes-incubator/external-storage#871]
Hello.

Please help, I deploy cephfs storageclass, add admin secret, but when i create claim i receive error:
`I0723 13:11:56.004099       1 leaderelection.go:156] attempting to acquire leader lease...
I0723 13:11:56.010280       1 leaderelection.go:178] successfully acquired lease to provision for pvc kube-test/claim1
I0723 13:11:56.012589       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-test", Name:"claim1", UID:"82da642a-8e58-11e8-be2c-005056b2b12a", APIVersion:"v1", ResourceVersion:"14539762", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-test/claim1"
E0723 13:12:08.235235       1 cephfs-provisioner.go:155] failed to provision share "kubernetes-dynamic-pvc-47bab9db-8e79-11e8-9700-ea04dd2539d0" for "kubernetes-dynamic-user-47baba31-8e79-11e8-9700-ea04dd2539d0", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 336, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 330, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 210, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 106, in volume_client
    self._volume_client.connect(None)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 471, in connect
    self.fs.mount()
  File "cephfs.pyx", line 548, in cephfs.LibCephFS.mount (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.0/rpm/el7/BUILD/ceph-13.2.0/build/src/pybind/cephfs/pyrex/cephfs.c:5648)
cephfs.Error: (110, 'error calling ceph_mount: error code 110')
E0723 13:12:08.235338       1 controller.go:1068] Failed to provision volume for claim "kube-test/claim1" with StorageClass "cephfs": exit status 1
I0723 13:12:08.235455       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-test", Name:"claim1", UID:"82da642a-8e58-11e8-be2c-005056b2b12a", APIVersion:"v1", ResourceVersion:"14538742", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "cephfs": exit status 1
I0723 13:12:26.159211       1 leaderelection.go:204] stopped trying to renew lease to provision for pvc kube-test/claim1, timeout reached`

**Comment by deniskril** [comment]
when I create a manual pv, then everything works
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-test
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  cephfs:
    monitors:
      - 10.1.1.1:6789
      - 10.1.1.2:6789
      - 10.1.1.3:6789
    user: kubetnetes
    secretRef:
      name: cephfs-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Retain`

StorageClass.yaml:
`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
    monitors: 10.1.1.1:6789, 10.1.1.2:6789, 10.1.1.3:6789
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: "cephfs"
    claimRoot: /volumes/kubernetes`

directory /volumes/kubernetes will be created on kube nodes?

**Comment by wongma7** [comment]
No, it doesn't look like it creates the directory for you. The code says it only sets the environment variable CEPH_VOLUME_ROOT=/volumes/kubernetes. I am not familiar with ceph fs but it seems like you need to create /volumes/kubernetes beforehand, if that makes sense.

**Comment by deniskril** [comment]
How can i fix this problem?

**Comment by wongma7** [comment]
Actually I was wrong, it looks like the Ceph client creates the path for you https://github.com/ceph/ceph/blob/master/src/pybind/ceph_volume_client.py#L620 so /volumes/kubernetes is automatically created.

We need to see logs from the server/monitor side to find out what is wrong and fix it IMO, because the client is just silently timing out.

**Comment by wongma7** [comment]
You can also ask in kubernetes slack, #sig-storage maybe, maybe somebody there has some ceph fs expertise they can share...

**Comment by deniskril** [comment]
`2018-07-23 22:44:59.128728 7f00186f3700  1 mon.ceph-0@0(leader).mds e1 Client subscribed for legacy filesystem but none is configured
2018-07-23 22:45:06.292339 7f0018ef4700  0 mon.ceph-0@0(leader).data_health(6) update_stats avail 85% total 29101 MB, used 2745 MB, avail 24855 MB
2018-07-23 22:45:29.298417 7f00186f3700  1 mon.ceph-0@0(leader).mds e1 Client subscribed for legacy filesystem but none is configured
2018-07-23 22:45:34.416481 7f00186f3700  1 mon.ceph-0@0(leader).mds e1 Client subscribed for legacy filesystem but none is configured
2018-07-23 22:45:48.622826 7f00186f3700  1 mon.ceph-0@0(leader).mds e1 Client subscribed for legacy filesystem but none is configured
2018-07-23 22:45:49.456603 7f00186f3700  1 mon.ceph-0@0(leader).mds e1 Client subscribed for legacy filesystem but none is configured
2018-07-23 22:46:06.292652 7f0018ef4700  0 mon.ceph-0@0(leader).data_health(6) update_stats avail 85% total 29101 MB, used 2745 MB, avail 24855 MB
2018-07-23 22:46:08.725530 7f00186f3700  1 mon.ceph-0@0(leader).mds e1 Client subscribed for legacy filesystem but none is configured
2018-07-23 22:46:29.584159 7f00186f3700  0 -- 10.79.65.24:6789/0 submit_message mon_map magic: 0 v1 remote, 10.1.1.16:0/1751770959, failed lossy con, dropping message 0x564a83f926c0
2018-07-23 22:46:29.620179 7f00186f3700  0 -- 10.79.65.24:6789/0 submit_message mon_map magic: 0 v1 remote, 10.1.1.16:0/2815418488, failed lossy con, dropping message 0x564a83f94640`

10.1.1.16 - kube-node

**Comment by wongma7** [comment]
@cofyc do you know what "Client subscribed for legacy filesystem but none is configured" means? ty~

**Comment by deniskril** [comment]
log from kube-node:
`Jul 23 23:12:21 kube-node6 ceph-create-keys[12319]: admin_socket: exception getting command descriptions: [Errno 2] No such file or directory
Jul 23 23:12:21 kube-node6 ceph-create-keys[12319]: INFO:ceph-create-keys:ceph-mon admin socket not ready yet.
Jul 23 23:12:22 kube-node6 ceph-create-keys[12319]: admin_socket: exception getting command descriptions: [Errno 2] No such file or directory
Jul 23 23:12:22 kube-node6 ceph-create-keys[12319]: INFO:ceph-create-keys:ceph-mon admin socket not ready yet.`

**Comment by cofyc** [comment]
I don't know either

**Comment by FengyunPan2** [comment]
I encountered the same issue too.

**Comment by FengyunPan2** [comment]
E0816 08:01:25.213297       1 cephfs-provisioner.go:155] failed to provision share "kubernetes-dynamic-pvc-df710873-a129-11e8-87d5-02420a643e1a" for "kubernetes-dynamic-user-df7108e0-a129-11e8-87d5-02420a643e1a", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 336, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 330, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 210, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 106, in volume_client
    self._volume_client.connect(None)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 471, in connect
    self.fs.mount()
  File "cephfs.pyx", line 548, in cephfs.LibCephFS.mount (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/cephfs/pyrex/cephfs.c:5648)
cephfs.Error: (110, 'error calling ceph_mount: error code 110')

**Comment by pehlert** [comment]
If this happens to you, make sure you have an MDS server running in your ceph cluster. Otherwise the provisioner will wait for a response from MDS for a long time and abort eventually.

**Comment by geosword** [comment]
For me, I hadnt yet created a ceph file system with 
```
ceph fs new...
```
